### ISSUE TITLE
[Zenith] L-4 Unwanted panic while normalizing points to affine

### ISSUE THREAD

**Issue by manishbista28** [alpenlabs/g16#27]
### Target

- [src/gadgets/bn254/pairing.rs](https://github.com/alpenlabs/g16/blob/7d7e002ac9a78700e475750dd45a3672edf394f7/src/gadgets/bn254/pairing.rs#L173)
- [src/gadgets/bn254/pairing.rs](https://github.com/alpenlabs/g16/blob/7d7e002ac9a78700e475750dd45a3672edf394f7/src/gadgets/bn254/pairing.rs#L188)

### Severity:

- Impact: Low
- Likelihood: Low

### Description:
The functions `g1_normalize_to_affine` and `g2_normalize_to_affine` normalizes the projective points to affine. This method however does not take into account the point at infinity and will cause unwanted panic while trying to convert a point at infinity projective point to affine since the point and infinity has z component 0 and `Fq::inverse_montgomery` (or Fq2::inverse_montgomery) will panic for 0. Same issue has been raised earlier here: https://github.com/zenith-security/2025-11-alpen-labs/issues/1. It should be noted that the arkworks handles the point and infinity conversion i.e., converting a infinity point from projective coordinates to affine does not panic due to their [`Affine`](https://github.com/arkworks-rs/algebra/blob/c1f4f5665504154a9de2345f464b0b3da72c28ec/ec/src/models/short_weierstrass/affine.rs#L30) representation which can also represent points at infinity. Since the circuit implementation intended to follow the implementation compatible with arkworks, the edge cases should be compatible as well(in this case the point at infinity).

### Recommendations:

Add explicit zero check in those functions to handle points at infinity as well so that unwanted panic can be avoided.

**Client:**

**Zenith:**

**Comment by manishbista28** [comment]
Relates to #20

**Comment by AaronFeickert** [comment]
@manishbista28 is this addressed by #37?

**Comment by manishbista28** [comment]
@AaronFeickert It's not fixed yet but the problem is in code that we do not use at all. 
So it will either be a "Won't Fix" or we might create a PR to remove the problematic unused code.
